#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x81C24FF12FB7B14B (philnelson@acm.org)
#
Name     : bc
Version  : 1.07.1
Release  : 20
URL      : https://mirrors.kernel.org/gnu/bc/bc-1.07.1.tar.gz
Source0  : https://mirrors.kernel.org/gnu/bc/bc-1.07.1.tar.gz
Source99 : https://mirrors.kernel.org/gnu/bc/bc-1.07.1.tar.gz.sig
Summary  : An arbitrary precision calculator language
Group    : Development/Tools
License  : GPL-2.0+ GPL-3.0 LGPL-3.0
Requires: bc-bin = %{version}-%{release}
Requires: bc-license = %{version}-%{release}
Requires: bc-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : ed
BuildRequires : flex
BuildRequires : texinfo

%description
GNU bc version 1.07:
Extra configuration options:
--with-readline tells bc to use the readline package that allows
for editing input lines when run interactive.

%package bin
Summary: bin components for the bc package.
Group: Binaries
Requires: bc-license = %{version}-%{release}

%description bin
bin components for the bc package.


%package doc
Summary: doc components for the bc package.
Group: Documentation
Requires: bc-man = %{version}-%{release}

%description doc
doc components for the bc package.


%package license
Summary: license components for the bc package.
Group: Default

%description license
license components for the bc package.


%package man
Summary: man components for the bc package.
Group: Default

%description man
man components for the bc package.


%prep
%setup -q -n bc-1.07.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557075430
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557075430
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bc
cp COPYING %{buildroot}/usr/share/package-licenses/bc/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/bc/COPYING.LIB
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bc
/usr/bin/dc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bc/COPYING
/usr/share/package-licenses/bc/COPYING.LIB

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bc.1
/usr/share/man/man1/dc.1
