#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x81C24FF12FB7B14B (philnelson@acm.org)
#
Name     : bc
Version  : 1.07.1
Release  : 21
URL      : https://mirrors.kernel.org/gnu/bc/bc-1.07.1.tar.gz
Source0  : https://mirrors.kernel.org/gnu/bc/bc-1.07.1.tar.gz
Source1 : https://mirrors.kernel.org/gnu/bc/bc-1.07.1.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0+ GPL-3.0 LGPL-3.0
Requires: bc-bin = %{version}-%{release}
Requires: bc-info = %{version}-%{release}
Requires: bc-license = %{version}-%{release}
Requires: bc-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : ed
BuildRequires : flex
BuildRequires : texinfo

%description
GNU bc version 1.07:
Extra configuration options:
--with-readline tells bc to use the readline package that allows
for editing input lines when run interactive.

%package bin
Summary: bin components for the bc package.
Group: Binaries
Requires: bc-license = %{version}-%{release}

%description bin
bin components for the bc package.


%package info
Summary: info components for the bc package.
Group: Default

%description info
info components for the bc package.


%package license
Summary: license components for the bc package.
Group: Default

%description license
license components for the bc package.


%package man
Summary: man components for the bc package.
Group: Default

%description man
man components for the bc package.


%prep
%setup -q -n bc-1.07.1
cd %{_builddir}/bc-1.07.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1573770999
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1573770999
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bc
cp %{_builddir}/bc-1.07.1/COPYING %{buildroot}/usr/share/package-licenses/bc/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/bc-1.07.1/COPYING.LIB %{buildroot}/usr/share/package-licenses/bc/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bc
/usr/bin/dc

%files info
%defattr(0644,root,root,0755)
/usr/share/info/bc.info
/usr/share/info/dc.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bc/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/bc/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bc.1
/usr/share/man/man1/dc.1
