#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x81C24FF12FB7B14B (philnelson@acm.org)
#
Name     : bc
Version  : 1.07.1
Release  : 18
URL      : https://mirrors.kernel.org/gnu/bc/bc-1.07.1.tar.gz
Source0  : https://mirrors.kernel.org/gnu/bc/bc-1.07.1.tar.gz
Source99 : https://mirrors.kernel.org/gnu/bc/bc-1.07.1.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0+ GPL-3.0 LGPL-3.0
Requires: bc-bin
Requires: bc-doc
BuildRequires : bison
BuildRequires : ed
BuildRequires : flex
BuildRequires : texinfo

%description
GNU bc version 1.07:
Extra configuration options:
--with-readline tells bc to use the readline package that allows
for editing input lines when run interactive.

%package bin
Summary: bin components for the bc package.
Group: Binaries

%description bin
bin components for the bc package.


%package doc
Summary: doc components for the bc package.
Group: Documentation

%description doc
doc components for the bc package.


%prep
%setup -q -n bc-1.07.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1520829177
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1520829177
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bc
/usr/bin/dc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
